#!/bin/bash
set +x
set -e
. .colors.sh

BASEDIR=$PWD
. $BASEDIR/io.sh 1 7 14 "$@"
CURDIR=`pwd`
## INPUTS VARIABLES
inputs_zip=${INPUTS1}


## PARAMETERS VARIABLES
SFTMP=${PARAMS1}
SMTMP=${PARAMS2}
SMFMX=${PARAMS3}
SMFMN=${PARAMS4}
TIMP=${PARAMS5}
YEARS=${PARAMS6}
START_YEAR=${PARAMS7}


set -xe

####### WRITE YOUR INVOCATION LINE AFTER THIS COMMENT

cp -rv swat670 inputs/swat670
    
pushd inputs
./swat670
popd

set +x
echo -e "$(c G)[success] The model has exited with code SUCCESS"
####### WRITE YOUR INVOCATION LINE BEFORE THIS COMMENT
cd $BASEDIR
. $BASEDIR/output.sh